import { Salsa , Oleo_Script} from 'next/font/google'
import './globals.css'

export const salsa = Salsa({ subsets: ['latin'] , weight: '400' })
export const oleo_script = Oleo_Script({subsets : ['latin'] , weight: ['400', '700'],} , )

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={salsa.className}>{children}</body>
    </html>
  )
}
